# SERVER
server.port=8080
spring.application.name=signbridge-backend

# DATABASE — PostgreSQL (Real Database)
spring.datasource.url=jdbc:postgresql://localhost:5432/signbridge_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=signbridge123

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=signbridge-super-secret-key-minimum-32-characters-long
jwt.expiration=86400000

# ML SERVICE
ml.service.url=http://localhost:8000

# LOGGING
logging.level.com.signbridge=DEBUG
